
services:
  # 🟢 FRONTEND: Vue.js Uygulamamız
  frontend:
    build:
      context: ./first-vue-project
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./first-vue-project/src:/app/src

  # 📦 BACKEND 1: Ürün Mikroservisimiz
  urun-servisi:
    build:
      context: ./Product Service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=database
      - DB_USER=nuri
      - DB_PASSWORD=aycan_secret
      - DB_NAME=product_db
      - DB_PORT=5432
      - STOCK_API_URL=http://stok-servisi:5002/
    depends_on:
       database:
          condition: service_healthy

  # 📦 BACKEND 2: Stok Mikroservisimiz (Yeni Eklenen)
  stok-servisi:
    build:
      context: ./stock-service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - DB_HOST=database
      - DB_USER=nuri
      - DB_PASSWORD=aycan_secret
      - DB_NAME=stock_db
      - DB_PORT=5432
    depends_on:
       database:
          condition: service_healthy

 # 🐘 VERİTABANI: Ortak PostgreSQL Konteynerimiz
  database:
    build:
      context: .
      dockerfile: Dockerfile.postgres # 👈 Dışarıdan bağlamak yerine imajı kendimiz örüyoruz
    container_name: ortak_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=nuri
      - POSTGRES_PASSWORD=aycan_secret
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nuri -d product_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata_nihai:/var/lib/postgresql/data

      # 🌐 GÖRSEL PANEL: pgAdmin Konteynerimiz (Yeni Eklenen)
  pgadmin:
    image: dpage/pgadmin4:8.5
    container_name: panel_pgadmin
    ports:
      - "8080:80" # Tarayıcıdan 8080 portu ile erişeceğiz
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@nuri.com   # Giriş paneli e-postası
      - PGADMIN_DEFAULT_PASSWORD=admin_secret  # Giriş paneli şifresi
    depends_on:
      - database

# 🚪 API GATEWAY: Tüm Mikroservislerin Tek Giriş Kapısı
  api-gateway:
    image: nginx:1.25-alpine
    container_name: merkezi_gateway
    ports:
      - "8000:8000" # Dış dünyaya sadece 8000 portunu açıyoruz
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro # Konfigürasyon dosyasını bağladık (Read-Only)
    depends_on:
      - urun-servisi
      - stok-servisi
volumes:
  pgdata_nihai:
