version: '3.8'

services:
  # 🟢 FRONTEND: Vue.js Uygulamamız
  frontend:
    build:
      context: ./first-vue-project
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./first-vue-project/src:/app/src

  # 📦 BACKEND 1: Ürün Mikroservisimiz
  urun-servisi:
    build:
      context: ./Product Service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./Product Service:/app
      - /app/node_modules
    environment:
      - DB_HOST=database
      - DB_USER=nuri
      - DB_PASSWORD=aycan_secret
      - DB_NAME=product_db
      - DB_PORT=5432
    depends_on:
      - database

  # 📦 BACKEND 2: Stok Mikroservisimiz (Yeni Eklenen)
  stok-servisi:
    build:
      context: ./stock-service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./stock-service:/app
      - /app/node_modules
    environment:
      - DB_HOST=database
      - DB_USER=nuri
      - DB_PASSWORD=aycan_secret
      - DB_NAME=stock_db
      - DB_PORT=5432
    depends_on:
      - database

 # 🐘 VERİTABANI: Ortak PostgreSQL Konteynerimiz
  database:
    build:
      context: .
      dockerfile: Dockerfile.postgres # 👈 Dışarıdan bağlamak yerine imajı kendimiz örüyoruz
    container_name: ortak_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=nuri
      - POSTGRES_PASSWORD=aycan_secret
      - POSTGRES_DB=product_db 
    volumes:
      - pgdata_nihai:/var/lib/postgresql/data

      # 🌐 GÖRSEL PANEL: pgAdmin Konteynerimiz (Yeni Eklenen)
  pgadmin:
    image: dpage/pgadmin4:8.5
    container_name: panel_pgadmin
    ports:
      - "8080:80" # Tarayıcıdan 8080 portu ile erişeceğiz
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@nuri.com   # Giriş paneli e-postası
      - PGADMIN_DEFAULT_PASSWORD=admin_secret  # Giriş paneli şifresi
    depends_on:
      - database

volumes:
  pgdata_nihai:
